package app.marmalade.android.ui.sessions

/**
 * Hand-curated emoji catalog for [EmojiPickerSheet]. Each entry has search keywords
 * (lowercase, space-separated) used by the search bar's substring match.
 *
 * Scope: Emoji 13.1 baseline and earlier — renders natively on Android 12+ (minSdk 31)
 * without needing the emoji2 font polyfill. Avoid Emoji 14+ additions (e.g. melting face,
 * saluting face, holding back tears) unless the project later adds
 * `androidx.emoji2:emoji2-bundled`.
 */
internal data class EmojiEntry(val emoji: String, val keywords: String)
internal data class EmojiCategory(val label: String, val icon: String, val entries: List<EmojiEntry>)

internal val EMOJI_DATA: List<EmojiCategory> = listOf(
    EmojiCategory("Smileys & Emotion", "😀", listOf(
        EmojiEntry("😀", "grinning face happy smile"),
        EmojiEntry("😃", "smiley happy big eyes"),
        EmojiEntry("😄", "smile grin happy laugh"),
        EmojiEntry("😁", "beaming grin teeth"),
        EmojiEntry("😆", "laughing squinting xd"),
        EmojiEntry("😅", "sweat smile awkward"),
        EmojiEntry("🤣", "rofl rolling floor laughing"),
        EmojiEntry("😂", "joy tears laughing lol"),
        EmojiEntry("🙂", "slight smile content"),
        EmojiEntry("🙃", "upside down silly"),
        EmojiEntry("😉", "wink winking"),
        EmojiEntry("😊", "blush shy happy"),
        EmojiEntry("😇", "innocent angel halo"),
        EmojiEntry("🥰", "smiling hearts love adore"),
        EmojiEntry("😍", "heart eyes love"),
        EmojiEntry("🤩", "star struck excited"),
        EmojiEntry("😘", "kiss blowing"),
        EmojiEntry("😗", "kissing"),
        EmojiEntry("☺️", "relaxed smiling content"),
        EmojiEntry("😚", "kissing closed eyes"),
        EmojiEntry("😙", "kissing smiling"),
        EmojiEntry("🥲", "smiling tear bittersweet"),
        EmojiEntry("😋", "yum delicious savor tasty"),
        EmojiEntry("😛", "tongue out playful"),
        EmojiEntry("😜", "winking tongue silly"),
        EmojiEntry("🤪", "zany goofy crazy"),
        EmojiEntry("😝", "squinting tongue"),
        EmojiEntry("🤑", "money face rich"),
        EmojiEntry("🤗", "hugging hug"),
        EmojiEntry("🤭", "hand over mouth giggle oops"),
        EmojiEntry("🤫", "shushing quiet shh"),
        EmojiEntry("🤔", "thinking hmm"),
        EmojiEntry("🤐", "zipper mouth shut"),
        EmojiEntry("🤨", "raised eyebrow skeptical"),
        EmojiEntry("😐", "neutral face meh"),
        EmojiEntry("😑", "expressionless blank"),
        EmojiEntry("😶", "no mouth silent"),
        EmojiEntry("😏", "smirk smug"),
        EmojiEntry("😒", "unamused annoyed"),
        EmojiEntry("🙄", "eye roll rolling eyes"),
        EmojiEntry("😬", "grimacing awkward teeth"),
        EmojiEntry("🤥", "lying pinocchio"),
        EmojiEntry("😌", "relieved content calm"),
        EmojiEntry("😔", "pensive sad thoughtful"),
        EmojiEntry("😪", "sleepy drowsy"),
        EmojiEntry("🤤", "drooling"),
        EmojiEntry("😴", "sleeping zzz"),
        EmojiEntry("😷", "mask medical sick"),
        EmojiEntry("🤒", "thermometer sick fever"),
        EmojiEntry("🤕", "bandage hurt injured"),
        EmojiEntry("🤢", "nauseated sick gross"),
        EmojiEntry("🤮", "vomiting throwing up"),
        EmojiEntry("🤧", "sneezing cold tissue"),
        EmojiEntry("🥵", "hot sweating face"),
        EmojiEntry("🥶", "cold freezing face"),
        EmojiEntry("🥴", "woozy dizzy drunk"),
        EmojiEntry("😵", "dizzy ko knocked out"),
        EmojiEntry("😵‍💫", "spiral dizzy confused"),
        EmojiEntry("🤯", "mind blown explode shocked"),
        EmojiEntry("🤠", "cowboy hat"),
        EmojiEntry("🥳", "partying birthday celebrate party"),
        EmojiEntry("🥸", "disguised glasses mustache"),
        EmojiEntry("😎", "sunglasses cool"),
        EmojiEntry("🤓", "nerd glasses"),
        EmojiEntry("🧐", "monocle detective inspect"),
        EmojiEntry("😕", "confused unsure"),
        EmojiEntry("😟", "worried concerned"),
        EmojiEntry("🙁", "slightly frowning"),
        EmojiEntry("☹️", "frowning sad"),
        EmojiEntry("😮", "open mouth wow surprised"),
        EmojiEntry("😯", "hushed quiet"),
        EmojiEntry("😲", "astonished shocked"),
        EmojiEntry("😳", "flushed embarrassed"),
        EmojiEntry("🥺", "pleading puppy eyes begging"),
        EmojiEntry("😦", "frowning open mouth"),
        EmojiEntry("😧", "anguished pained"),
        EmojiEntry("😨", "fearful afraid scared"),
        EmojiEntry("😰", "anxious sweat scared"),
        EmojiEntry("😥", "sad disappointed"),
        EmojiEntry("😢", "crying tear sad"),
        EmojiEntry("😭", "sobbing crying loud bawl"),
        EmojiEntry("😱", "scream horror shocked"),
        EmojiEntry("😖", "confounded"),
        EmojiEntry("😣", "persevering struggling"),
        EmojiEntry("😞", "disappointed sad"),
        EmojiEntry("😓", "downcast sweat tired"),
        EmojiEntry("😩", "weary tired"),
        EmojiEntry("😫", "tired exhausted"),
        EmojiEntry("🥱", "yawning bored tired"),
        EmojiEntry("😤", "huffing triumph determined"),
        EmojiEntry("😡", "pouting angry rage red"),
        EmojiEntry("😠", "angry frustrated mad"),
        EmojiEntry("🤬", "cursing swearing angry"),
        EmojiEntry("😈", "devil imp evil purple"),
        EmojiEntry("👿", "angry devil imp"),
        EmojiEntry("💀", "skull dead death"),
        EmojiEntry("☠️", "skull crossbones danger"),
        EmojiEntry("💩", "poop poo"),
        EmojiEntry("🤡", "clown face"),
        EmojiEntry("👹", "ogre japanese demon"),
        EmojiEntry("👺", "goblin tengu japanese"),
        EmojiEntry("👻", "ghost boo spooky"),
        EmojiEntry("👽", "alien ufo space"),
        EmojiEntry("👾", "alien monster space invader"),
        EmojiEntry("🤖", "robot bot machine"),
        EmojiEntry("😺", "grinning cat"),
        EmojiEntry("😸", "grinning eyes cat"),
        EmojiEntry("😹", "joy tears cat"),
        EmojiEntry("😻", "heart eyes cat"),
        EmojiEntry("😼", "smirk cat"),
        EmojiEntry("😽", "kiss cat"),
        EmojiEntry("🙀", "weary cat shocked"),
        EmojiEntry("😿", "crying cat"),
        EmojiEntry("😾", "pouting angry cat"),
        EmojiEntry("🙈", "see no evil monkey"),
        EmojiEntry("🙉", "hear no evil monkey"),
        EmojiEntry("🙊", "speak no evil monkey"),
    )),
    EmojiCategory("People & Body", "🤝", listOf(
        EmojiEntry("👋", "wave hi hello hand"),
        EmojiEntry("🤚", "raised back hand stop"),
        EmojiEntry("🖐️", "raised hand fingers splayed"),
        EmojiEntry("✋", "raised hand stop high five"),
        EmojiEntry("🖖", "vulcan spock star trek"),
        EmojiEntry("👌", "ok hand"),
        EmojiEntry("🤌", "pinched fingers italian"),
        EmojiEntry("🤏", "pinching small tiny"),
        EmojiEntry("✌️", "peace victory hand"),
        EmojiEntry("🤞", "fingers crossed luck hope"),
        EmojiEntry("🤟", "love you sign ily"),
        EmojiEntry("🤘", "rock on horns metal"),
        EmojiEntry("🤙", "call me hang loose shaka"),
        EmojiEntry("👈", "backhand index left point"),
        EmojiEntry("👉", "backhand index right point"),
        EmojiEntry("👆", "backhand index up point"),
        EmojiEntry("🖕", "middle finger"),
        EmojiEntry("👇", "backhand index down point"),
        EmojiEntry("☝️", "index pointing up"),
        EmojiEntry("👍", "thumbs up like yes approve"),
        EmojiEntry("👎", "thumbs down dislike no"),
        EmojiEntry("✊", "raised fist solidarity"),
        EmojiEntry("👊", "fist punch bump"),
        EmojiEntry("🤛", "left fist bump"),
        EmojiEntry("🤜", "right fist bump"),
        EmojiEntry("👏", "clapping applause"),
        EmojiEntry("🙌", "raising hands praise celebration"),
        EmojiEntry("👐", "open hands"),
        EmojiEntry("🤲", "palms together up"),
        EmojiEntry("🤝", "handshake deal agreement"),
        EmojiEntry("🙏", "folded hands prayer please thanks namaste"),
        EmojiEntry("✍️", "writing hand"),
        EmojiEntry("💅", "nail polish manicure"),
        EmojiEntry("🤳", "selfie phone"),
        EmojiEntry("💪", "muscle strong flex bicep"),
        EmojiEntry("🦾", "mechanical arm prosthetic"),
        EmojiEntry("🦿", "mechanical leg prosthetic"),
        EmojiEntry("🦵", "leg"),
        EmojiEntry("🦶", "foot"),
        EmojiEntry("👂", "ear"),
        EmojiEntry("🦻", "ear hearing aid"),
        EmojiEntry("👃", "nose"),
        EmojiEntry("🧠", "brain"),
        EmojiEntry("🫀", "anatomical heart organ"),
        EmojiEntry("🫁", "lungs breathe"),
        EmojiEntry("🦷", "tooth"),
        EmojiEntry("🦴", "bone"),
        EmojiEntry("👀", "eyes"),
        EmojiEntry("👁️", "eye see watch"),
        EmojiEntry("👅", "tongue"),
        EmojiEntry("👄", "mouth lips"),
        EmojiEntry("👶", "baby infant"),
        EmojiEntry("🧒", "child kid"),
        EmojiEntry("👦", "boy"),
        EmojiEntry("👧", "girl"),
        EmojiEntry("🧑", "person adult"),
        EmojiEntry("👱", "blond"),
        EmojiEntry("👨", "man"),
        EmojiEntry("👩", "woman"),
        EmojiEntry("🧓", "older person elder"),
        EmojiEntry("👴", "old man grandfather"),
        EmojiEntry("👵", "old woman grandmother"),
        EmojiEntry("🙅", "person no gesture nope"),
        EmojiEntry("🙆", "person ok gesture"),
        EmojiEntry("💁", "information person tipping hand"),
        EmojiEntry("🙋", "hand raised volunteering"),
        EmojiEntry("🙇", "bowing apology sorry"),
        EmojiEntry("🤦", "facepalm"),
        EmojiEntry("🤷", "shrug dont know"),
        EmojiEntry("🧑‍⚕️", "health worker doctor nurse medical"),
        EmojiEntry("🧑‍🎓", "student graduate"),
        EmojiEntry("🧑‍🏫", "teacher professor"),
        EmojiEntry("🧑‍⚖️", "judge legal court"),
        EmojiEntry("🧑‍🌾", "farmer"),
        EmojiEntry("🧑‍🍳", "cook chef"),
        EmojiEntry("🧑‍🔧", "mechanic"),
        EmojiEntry("🧑‍🏭", "factory worker"),
        EmojiEntry("🧑‍💼", "office worker business"),
        EmojiEntry("🧑‍🔬", "scientist research lab"),
        EmojiEntry("🧑‍💻", "technologist coder programmer developer"),
        EmojiEntry("🧑‍🎤", "singer musician"),
        EmojiEntry("🧑‍🎨", "artist painter creative"),
        EmojiEntry("🧑‍✈️", "pilot"),
        EmojiEntry("🧑‍🚀", "astronaut space"),
        EmojiEntry("🧑‍🚒", "firefighter"),
        EmojiEntry("👮", "police officer cop"),
        EmojiEntry("🕵️", "detective spy"),
        EmojiEntry("💂", "guard"),
        EmojiEntry("🥷", "ninja"),
        EmojiEntry("👷", "construction worker hard hat"),
        EmojiEntry("🤴", "prince"),
        EmojiEntry("👸", "princess"),
        EmojiEntry("👳", "turban"),
        EmojiEntry("👲", "cap chinese"),
        EmojiEntry("🧕", "woman headscarf hijab"),
        EmojiEntry("🤵", "person tuxedo suit"),
        EmojiEntry("👰", "person veil bride wedding"),
        EmojiEntry("🤰", "pregnant"),
        EmojiEntry("🤱", "breast feeding"),
        EmojiEntry("👼", "baby angel"),
        EmojiEntry("🎅", "santa claus christmas"),
        EmojiEntry("🤶", "mrs claus christmas"),
        EmojiEntry("🦸", "superhero power"),
        EmojiEntry("🦹", "supervillain evil"),
        EmojiEntry("🧙", "mage wizard magic"),
        EmojiEntry("🧚", "fairy magic tiny"),
        EmojiEntry("🧛", "vampire dracula"),
        EmojiEntry("🧜", "merperson mermaid"),
        EmojiEntry("🧝", "elf"),
        EmojiEntry("🧞", "genie lamp wish"),
        EmojiEntry("🧟", "zombie undead"),
        EmojiEntry("💆", "face massage spa"),
        EmojiEntry("💇", "haircut salon"),
        EmojiEntry("🚶", "walking pedestrian"),
        EmojiEntry("🧍", "standing"),
        EmojiEntry("🧎", "kneeling"),
        EmojiEntry("🏃", "running runner jogging"),
        EmojiEntry("💃", "dancing woman"),
        EmojiEntry("🕺", "dancing man"),
        EmojiEntry("🧖", "sauna spa steam"),
        EmojiEntry("🧗", "climbing rock"),
        EmojiEntry("🧘", "lotus meditation yoga"),
        EmojiEntry("🛀", "bath tub bathing"),
        EmojiEntry("🛌", "sleeping bed"),
        EmojiEntry("👫", "couple holding hands"),
        EmojiEntry("👬", "men holding hands"),
        EmojiEntry("👭", "women holding hands"),
        EmojiEntry("💏", "kiss couple"),
        EmojiEntry("💑", "couple heart love"),
        EmojiEntry("👪", "family"),
        EmojiEntry("🗣️", "speaking head talking"),
        EmojiEntry("👤", "silhouette person profile"),
        EmojiEntry("👥", "silhouettes people group"),
        EmojiEntry("👣", "footprints"),
    )),
    EmojiCategory("Animals & Nature", "🐻", listOf(
        EmojiEntry("🐶", "dog puppy face"),
        EmojiEntry("🐕", "dog"),
        EmojiEntry("🦮", "guide dog service"),
        EmojiEntry("🐩", "poodle"),
        EmojiEntry("🐺", "wolf"),
        EmojiEntry("🦊", "fox"),
        EmojiEntry("🦝", "raccoon"),
        EmojiEntry("🐱", "cat kitten face"),
        EmojiEntry("🐈", "cat"),
        EmojiEntry("🐈‍⬛", "black cat"),
        EmojiEntry("🦁", "lion"),
        EmojiEntry("🐯", "tiger face"),
        EmojiEntry("🐅", "tiger"),
        EmojiEntry("🐆", "leopard cheetah"),
        EmojiEntry("🐴", "horse face"),
        EmojiEntry("🐎", "horse"),
        EmojiEntry("🦄", "unicorn"),
        EmojiEntry("🦓", "zebra"),
        EmojiEntry("🦌", "deer"),
        EmojiEntry("🦬", "bison buffalo"),
        EmojiEntry("🐮", "cow face"),
        EmojiEntry("🐂", "ox"),
        EmojiEntry("🐃", "water buffalo"),
        EmojiEntry("🐄", "cow"),
        EmojiEntry("🐷", "pig face"),
        EmojiEntry("🐖", "pig"),
        EmojiEntry("🐗", "boar"),
        EmojiEntry("🐽", "pig nose"),
        EmojiEntry("🐏", "ram"),
        EmojiEntry("🐑", "sheep"),
        EmojiEntry("🐐", "goat"),
        EmojiEntry("🐪", "camel"),
        EmojiEntry("🐫", "two hump camel bactrian"),
        EmojiEntry("🦙", "llama alpaca"),
        EmojiEntry("🦒", "giraffe"),
        EmojiEntry("🐘", "elephant"),
        EmojiEntry("🦣", "mammoth"),
        EmojiEntry("🦏", "rhinoceros"),
        EmojiEntry("🦛", "hippopotamus hippo"),
        EmojiEntry("🐭", "mouse face"),
        EmojiEntry("🐁", "mouse"),
        EmojiEntry("🐀", "rat"),
        EmojiEntry("🐹", "hamster"),
        EmojiEntry("🐰", "rabbit face bunny"),
        EmojiEntry("🐇", "rabbit bunny"),
        EmojiEntry("🐿️", "chipmunk squirrel"),
        EmojiEntry("🦫", "beaver"),
        EmojiEntry("🦔", "hedgehog"),
        EmojiEntry("🦇", "bat"),
        EmojiEntry("🐻", "bear"),
        EmojiEntry("🐻‍❄️", "polar bear"),
        EmojiEntry("🐨", "koala"),
        EmojiEntry("🐼", "panda"),
        EmojiEntry("🦥", "sloth"),
        EmojiEntry("🦦", "otter"),
        EmojiEntry("🦨", "skunk"),
        EmojiEntry("🦘", "kangaroo"),
        EmojiEntry("🦡", "badger"),
        EmojiEntry("🐾", "paw prints"),
        EmojiEntry("🦃", "turkey"),
        EmojiEntry("🐔", "chicken"),
        EmojiEntry("🐓", "rooster"),
        EmojiEntry("🐣", "hatching chick"),
        EmojiEntry("🐤", "baby chick"),
        EmojiEntry("🐥", "front facing chick"),
        EmojiEntry("🐦", "bird"),
        EmojiEntry("🐧", "penguin"),
        EmojiEntry("🕊️", "dove peace"),
        EmojiEntry("🦅", "eagle"),
        EmojiEntry("🦆", "duck"),
        EmojiEntry("🦢", "swan"),
        EmojiEntry("🦉", "owl"),
        EmojiEntry("🦤", "dodo"),
        EmojiEntry("🪶", "feather"),
        EmojiEntry("🦩", "flamingo"),
        EmojiEntry("🦚", "peacock"),
        EmojiEntry("🦜", "parrot"),
        EmojiEntry("🐸", "frog"),
        EmojiEntry("🐊", "crocodile alligator"),
        EmojiEntry("🐢", "turtle tortoise"),
        EmojiEntry("🦎", "lizard"),
        EmojiEntry("🐍", "snake"),
        EmojiEntry("🐲", "dragon face"),
        EmojiEntry("🐉", "dragon"),
        EmojiEntry("🦕", "sauropod dinosaur"),
        EmojiEntry("🦖", "trex tyrannosaurus dinosaur"),
        EmojiEntry("🐳", "spouting whale"),
        EmojiEntry("🐋", "whale"),
        EmojiEntry("🐬", "dolphin"),
        EmojiEntry("🦭", "seal"),
        EmojiEntry("🐟", "fish"),
        EmojiEntry("🐠", "tropical fish"),
        EmojiEntry("🐡", "blowfish puffer"),
        EmojiEntry("🦈", "shark"),
        EmojiEntry("🐙", "octopus"),
        EmojiEntry("🐚", "shell"),
        EmojiEntry("🪸", "coral"),
        EmojiEntry("🐌", "snail"),
        EmojiEntry("🦋", "butterfly"),
        EmojiEntry("🐛", "bug caterpillar"),
        EmojiEntry("🐜", "ant"),
        EmojiEntry("🐝", "bee honeybee"),
        EmojiEntry("🪲", "beetle"),
        EmojiEntry("🐞", "ladybug"),
        EmojiEntry("🦗", "cricket grasshopper"),
        EmojiEntry("🪳", "cockroach"),
        EmojiEntry("🕷️", "spider"),
        EmojiEntry("🕸️", "spider web"),
        EmojiEntry("🦂", "scorpion"),
        EmojiEntry("🦟", "mosquito"),
        EmojiEntry("🪰", "fly"),
        EmojiEntry("🪱", "worm"),
        EmojiEntry("🦠", "microbe germ virus"),
        EmojiEntry("💐", "bouquet flowers"),
        EmojiEntry("🌷", "tulip flower"),
        EmojiEntry("🌹", "rose flower"),
        EmojiEntry("🥀", "wilted flower"),
        EmojiEntry("🌺", "hibiscus flower"),
        EmojiEntry("🌸", "cherry blossom sakura"),
        EmojiEntry("🌼", "blossom flower"),
        EmojiEntry("🌻", "sunflower"),
        EmojiEntry("🌱", "seedling sprout"),
        EmojiEntry("🪴", "potted plant"),
        EmojiEntry("🌲", "evergreen tree pine"),
        EmojiEntry("🌳", "deciduous tree"),
        EmojiEntry("🌴", "palm tree tropical"),
        EmojiEntry("🌵", "cactus desert"),
        EmojiEntry("🌾", "rice sheaf wheat"),
        EmojiEntry("🌿", "herb leaf"),
        EmojiEntry("☘️", "shamrock clover luck"),
        EmojiEntry("🍀", "four leaf clover lucky"),
        EmojiEntry("🍁", "maple leaf canada"),
        EmojiEntry("🍂", "fallen leaves autumn"),
        EmojiEntry("🍃", "leaf wind"),
        EmojiEntry("🍄", "mushroom"),
        EmojiEntry("🌰", "chestnut nut"),
        EmojiEntry("🪵", "wood log"),
        EmojiEntry("🪨", "rock stone boulder"),
        EmojiEntry("🌍", "globe earth africa europe"),
        EmojiEntry("🌎", "globe americas world"),
        EmojiEntry("🌏", "globe asia australia"),
    )),
    EmojiCategory("Food & Drink", "🍕", listOf(
        EmojiEntry("🍏", "green apple"),
        EmojiEntry("🍎", "apple red fruit"),
        EmojiEntry("🍐", "pear"),
        EmojiEntry("🍊", "orange tangerine"),
        EmojiEntry("🍋", "lemon"),
        EmojiEntry("🍌", "banana"),
        EmojiEntry("🍉", "watermelon"),
        EmojiEntry("🍇", "grapes"),
        EmojiEntry("🍓", "strawberry"),
        EmojiEntry("🫐", "blueberries"),
        EmojiEntry("🍈", "melon"),
        EmojiEntry("🍒", "cherries"),
        EmojiEntry("🍑", "peach"),
        EmojiEntry("🥭", "mango"),
        EmojiEntry("🍍", "pineapple"),
        EmojiEntry("🥥", "coconut"),
        EmojiEntry("🥝", "kiwi fruit"),
        EmojiEntry("🍅", "tomato"),
        EmojiEntry("🍆", "eggplant aubergine"),
        EmojiEntry("🥑", "avocado"),
        EmojiEntry("🥦", "broccoli"),
        EmojiEntry("🥬", "leafy greens lettuce"),
        EmojiEntry("🥒", "cucumber gherkin"),
        EmojiEntry("🌶️", "hot pepper chili spicy"),
        EmojiEntry("🫑", "bell pepper"),
        EmojiEntry("🌽", "corn maize"),
        EmojiEntry("🥕", "carrot"),
        EmojiEntry("🫒", "olive"),
        EmojiEntry("🧄", "garlic"),
        EmojiEntry("🧅", "onion"),
        EmojiEntry("🥔", "potato"),
        EmojiEntry("🍠", "sweet potato yam"),
        EmojiEntry("🥐", "croissant"),
        EmojiEntry("🥯", "bagel"),
        EmojiEntry("🍞", "bread loaf"),
        EmojiEntry("🥖", "baguette french bread"),
        EmojiEntry("🫓", "flatbread naan"),
        EmojiEntry("🥨", "pretzel"),
        EmojiEntry("🥞", "pancakes"),
        EmojiEntry("🧇", "waffle"),
        EmojiEntry("🧀", "cheese"),
        EmojiEntry("🍖", "meat on bone"),
        EmojiEntry("🍗", "poultry leg drumstick"),
        EmojiEntry("🥩", "cut of meat steak"),
        EmojiEntry("🥓", "bacon"),
        EmojiEntry("🍔", "hamburger burger"),
        EmojiEntry("🍟", "french fries chips"),
        EmojiEntry("🍕", "pizza"),
        EmojiEntry("🌭", "hot dog"),
        EmojiEntry("🥪", "sandwich"),
        EmojiEntry("🌮", "taco"),
        EmojiEntry("🌯", "burrito wrap"),
        EmojiEntry("🫔", "tamale"),
        EmojiEntry("🥙", "stuffed flatbread"),
        EmojiEntry("🧆", "falafel"),
        EmojiEntry("🥚", "egg"),
        EmojiEntry("🍳", "fried egg cooking"),
        EmojiEntry("🥘", "shallow pan food paella"),
        EmojiEntry("🍲", "pot of food stew"),
        EmojiEntry("🫕", "fondue"),
        EmojiEntry("🥣", "bowl spoon cereal"),
        EmojiEntry("🥗", "green salad"),
        EmojiEntry("🍿", "popcorn"),
        EmojiEntry("🧈", "butter"),
        EmojiEntry("🧂", "salt"),
        EmojiEntry("🥫", "canned food"),
        EmojiEntry("🍱", "bento box"),
        EmojiEntry("🍘", "rice cracker"),
        EmojiEntry("🍙", "rice ball onigiri"),
        EmojiEntry("🍚", "cooked rice"),
        EmojiEntry("🍛", "curry rice"),
        EmojiEntry("🍜", "noodles ramen steaming"),
        EmojiEntry("🍝", "spaghetti pasta"),
        EmojiEntry("🍢", "oden skewer"),
        EmojiEntry("🍣", "sushi"),
        EmojiEntry("🍤", "fried shrimp tempura"),
        EmojiEntry("🍥", "fish cake narutomaki"),
        EmojiEntry("🥮", "moon cake"),
        EmojiEntry("🍡", "dango skewer"),
        EmojiEntry("🥟", "dumpling"),
        EmojiEntry("🥠", "fortune cookie"),
        EmojiEntry("🥡", "takeout box"),
        EmojiEntry("🦪", "oyster"),
        EmojiEntry("🍦", "soft serve ice cream"),
        EmojiEntry("🍧", "shaved ice"),
        EmojiEntry("🍨", "ice cream"),
        EmojiEntry("🍩", "donut doughnut"),
        EmojiEntry("🍪", "cookie"),
        EmojiEntry("🎂", "birthday cake"),
        EmojiEntry("🍰", "shortcake slice"),
        EmojiEntry("🧁", "cupcake"),
        EmojiEntry("🥧", "pie"),
        EmojiEntry("🍫", "chocolate bar"),
        EmojiEntry("🍬", "candy sweet"),
        EmojiEntry("🍭", "lollipop"),
        EmojiEntry("🍮", "custard pudding flan"),
        EmojiEntry("🍯", "honey pot"),
        EmojiEntry("🍼", "baby bottle"),
        EmojiEntry("🥛", "glass of milk"),
        EmojiEntry("☕", "coffee hot beverage"),
        EmojiEntry("🫖", "teapot"),
        EmojiEntry("🍵", "tea cup green"),
        EmojiEntry("🍶", "sake bottle"),
        EmojiEntry("🍾", "champagne bottle pop"),
        EmojiEntry("🍷", "wine glass"),
        EmojiEntry("🍸", "cocktail martini"),
        EmojiEntry("🍹", "tropical drink"),
        EmojiEntry("🍺", "beer mug"),
        EmojiEntry("🍻", "clinking beer mugs cheers"),
        EmojiEntry("🥂", "clinking glasses cheers toast"),
        EmojiEntry("🥃", "tumbler glass whiskey"),
        EmojiEntry("🥤", "cup straw drink soda"),
        EmojiEntry("🧋", "bubble tea boba"),
        EmojiEntry("🧃", "beverage box juice"),
        EmojiEntry("🧉", "mate yerba"),
        EmojiEntry("🧊", "ice cube"),
        EmojiEntry("🥢", "chopsticks"),
        EmojiEntry("🍽️", "fork knife plate"),
        EmojiEntry("🍴", "fork and knife"),
        EmojiEntry("🥄", "spoon"),
    )),
    EmojiCategory("Activities", "⚽", listOf(
        EmojiEntry("⚽", "soccer football"),
        EmojiEntry("🏀", "basketball"),
        EmojiEntry("🏈", "american football"),
        EmojiEntry("⚾", "baseball"),
        EmojiEntry("🥎", "softball"),
        EmojiEntry("🎾", "tennis"),
        EmojiEntry("🏐", "volleyball"),
        EmojiEntry("🏉", "rugby"),
        EmojiEntry("🥏", "frisbee disc"),
        EmojiEntry("🎱", "8 ball pool billiards"),
        EmojiEntry("🪀", "yoyo toy"),
        EmojiEntry("🏓", "ping pong table tennis paddle"),
        EmojiEntry("🏸", "badminton"),
        EmojiEntry("🏒", "ice hockey"),
        EmojiEntry("🏑", "field hockey"),
        EmojiEntry("🥍", "lacrosse"),
        EmojiEntry("🏏", "cricket bat"),
        EmojiEntry("🪃", "boomerang"),
        EmojiEntry("🥅", "goal net"),
        EmojiEntry("⛳", "golf flag hole"),
        EmojiEntry("🪁", "kite"),
        EmojiEntry("🏹", "bow arrow archery"),
        EmojiEntry("🎣", "fishing pole rod"),
        EmojiEntry("🤿", "diving mask snorkel"),
        EmojiEntry("🥊", "boxing glove"),
        EmojiEntry("🥋", "martial arts uniform karate"),
        EmojiEntry("🎽", "running shirt jersey"),
        EmojiEntry("🛹", "skateboard"),
        EmojiEntry("🛼", "roller skate"),
        EmojiEntry("🛷", "sled sledding"),
        EmojiEntry("⛸️", "ice skate"),
        EmojiEntry("🥌", "curling stone"),
        EmojiEntry("🎿", "skis"),
        EmojiEntry("⛷️", "skier"),
        EmojiEntry("🏂", "snowboarder"),
        EmojiEntry("🪂", "parachute skydiving"),
        EmojiEntry("🏋️", "weight lifting gym workout"),
        EmojiEntry("🤺", "fencing sword"),
        EmojiEntry("🤼", "wrestling"),
        EmojiEntry("🤸", "cartwheel gymnastics"),
        EmojiEntry("🤽", "water polo"),
        EmojiEntry("🤾", "handball"),
        EmojiEntry("🤹", "juggling"),
        EmojiEntry("🏆", "trophy winner award"),
        EmojiEntry("🏅", "sports medal"),
        EmojiEntry("🎖️", "military medal"),
        EmojiEntry("🥇", "gold medal first"),
        EmojiEntry("🥈", "silver medal second"),
        EmojiEntry("🥉", "bronze medal third"),
        EmojiEntry("🎗️", "reminder ribbon awareness"),
        EmojiEntry("🎫", "ticket admission"),
        EmojiEntry("🎟️", "admission tickets"),
        EmojiEntry("🎪", "circus tent"),
        EmojiEntry("🎭", "theatre masks performing arts"),
        EmojiEntry("🩰", "ballet shoes"),
        EmojiEntry("🎨", "art palette paint"),
        EmojiEntry("🎬", "clapperboard movie film"),
        EmojiEntry("🎤", "microphone sing karaoke"),
        EmojiEntry("🎧", "headphones music"),
        EmojiEntry("🎼", "musical score sheet"),
        EmojiEntry("🎵", "music note"),
        EmojiEntry("🎶", "music notes"),
        EmojiEntry("🎙️", "studio microphone podcast"),
        EmojiEntry("🎚️", "level slider audio"),
        EmojiEntry("🎛️", "control knobs mixer"),
        EmojiEntry("🎺", "trumpet"),
        EmojiEntry("🎷", "saxophone sax"),
        EmojiEntry("🪗", "accordion"),
        EmojiEntry("🎸", "guitar"),
        EmojiEntry("🪕", "banjo"),
        EmojiEntry("🎻", "violin fiddle"),
        EmojiEntry("🥁", "drum"),
        EmojiEntry("🪘", "long drum djembe"),
        EmojiEntry("🎲", "dice game"),
        EmojiEntry("♟️", "chess pawn"),
        EmojiEntry("🎮", "controller gaming game"),
        EmojiEntry("🕹️", "joystick gaming arcade"),
        EmojiEntry("🎰", "slot machine casino jackpot"),
        EmojiEntry("🎳", "bowling"),
        EmojiEntry("🧩", "puzzle piece jigsaw"),
        EmojiEntry("🪅", "pinata"),
        EmojiEntry("🃏", "joker playing card"),
        EmojiEntry("🀄", "mahjong red dragon"),
        EmojiEntry("🎴", "flower playing cards"),
        EmojiEntry("🧵", "thread sewing"),
        EmojiEntry("🪡", "sewing needle"),
        EmojiEntry("🧶", "yarn knitting"),
        EmojiEntry("🪢", "knot rope"),
    )),
    EmojiCategory("Travel & Places", "🚀", listOf(
        EmojiEntry("🏠", "house home"),
        EmojiEntry("🏡", "house with garden"),
        EmojiEntry("🏘️", "houses neighborhood"),
        EmojiEntry("🏚️", "derelict house abandoned"),
        EmojiEntry("🏗️", "building construction"),
        EmojiEntry("🏢", "office building"),
        EmojiEntry("🏬", "department store"),
        EmojiEntry("🏣", "japanese post office"),
        EmojiEntry("🏤", "post office"),
        EmojiEntry("🏥", "hospital"),
        EmojiEntry("🏦", "bank"),
        EmojiEntry("🏨", "hotel"),
        EmojiEntry("🏩", "love hotel"),
        EmojiEntry("🏪", "convenience store"),
        EmojiEntry("🏫", "school"),
        EmojiEntry("🏛️", "classical building museum"),
        EmojiEntry("⛪", "church"),
        EmojiEntry("🕌", "mosque"),
        EmojiEntry("🕍", "synagogue"),
        EmojiEntry("🛕", "hindu temple"),
        EmojiEntry("⛩️", "shinto shrine torii"),
        EmojiEntry("🕋", "kaaba"),
        EmojiEntry("🏰", "castle european"),
        EmojiEntry("🏯", "castle japanese"),
        EmojiEntry("🏟️", "stadium arena"),
        EmojiEntry("🎡", "ferris wheel"),
        EmojiEntry("🎢", "roller coaster amusement"),
        EmojiEntry("🎠", "carousel horse"),
        EmojiEntry("⛲", "fountain"),
        EmojiEntry("⛱️", "umbrella beach"),
        EmojiEntry("🏖️", "beach umbrella sand"),
        EmojiEntry("🏝️", "desert island"),
        EmojiEntry("🏜️", "desert"),
        EmojiEntry("🌋", "volcano"),
        EmojiEntry("⛰️", "mountain"),
        EmojiEntry("🏔️", "mountain snow capped"),
        EmojiEntry("🗻", "mount fuji"),
        EmojiEntry("🏕️", "camping"),
        EmojiEntry("⛺", "tent camping"),
        EmojiEntry("🏞️", "national park landscape"),
        EmojiEntry("🛣️", "motorway highway"),
        EmojiEntry("🛤️", "railway tracks"),
        EmojiEntry("🌅", "sunrise over mountains"),
        EmojiEntry("🌄", "sunrise mountain"),
        EmojiEntry("🌆", "cityscape dusk"),
        EmojiEntry("🌇", "sunset city"),
        EmojiEntry("🌃", "night stars city"),
        EmojiEntry("🌉", "bridge night"),
        EmojiEntry("🌌", "milky way galaxy"),
        EmojiEntry("🎑", "moon viewing ceremony"),
        EmojiEntry("🌠", "shooting star wish"),
        EmojiEntry("🎇", "sparkler"),
        EmojiEntry("🎆", "fireworks"),
        EmojiEntry("🗼", "tokyo tower"),
        EmojiEntry("🗽", "statue of liberty"),
        EmojiEntry("🗾", "japan map"),
        EmojiEntry("🧭", "compass"),
        EmojiEntry("🗺️", "world map"),
        EmojiEntry("🚀", "rocket launch space"),
        EmojiEntry("🛸", "ufo flying saucer alien"),
        EmojiEntry("🛰️", "satellite"),
        EmojiEntry("✈️", "airplane plane travel"),
        EmojiEntry("🛩️", "small airplane"),
        EmojiEntry("🛫", "airplane departure takeoff"),
        EmojiEntry("🛬", "airplane arrival landing"),
        EmojiEntry("🚁", "helicopter"),
        EmojiEntry("🚂", "locomotive steam train"),
        EmojiEntry("🚆", "train"),
        EmojiEntry("🚇", "metro subway"),
        EmojiEntry("🚊", "tram"),
        EmojiEntry("🚉", "station"),
        EmojiEntry("🚄", "high speed train bullet"),
        EmojiEntry("🚅", "high speed train"),
        EmojiEntry("🚈", "light rail"),
        EmojiEntry("🚝", "monorail"),
        EmojiEntry("🚞", "mountain railway"),
        EmojiEntry("🚋", "tram car"),
        EmojiEntry("🚃", "railway car"),
        EmojiEntry("🚎", "trolleybus"),
        EmojiEntry("🚌", "bus"),
        EmojiEntry("🚐", "minibus van"),
        EmojiEntry("🚍", "oncoming bus"),
        EmojiEntry("🚓", "police car"),
        EmojiEntry("🚔", "oncoming police car"),
        EmojiEntry("🚑", "ambulance"),
        EmojiEntry("🚒", "fire engine truck"),
        EmojiEntry("🚙", "suv"),
        EmojiEntry("🚗", "car automobile"),
        EmojiEntry("🚕", "taxi"),
        EmojiEntry("🚚", "delivery truck"),
        EmojiEntry("🚛", "articulated truck semi"),
        EmojiEntry("🚜", "tractor"),
        EmojiEntry("🏎️", "racing car"),
        EmojiEntry("🏍️", "motorcycle"),
        EmojiEntry("🛵", "scooter motor"),
        EmojiEntry("🦽", "manual wheelchair"),
        EmojiEntry("🦼", "motorized wheelchair"),
        EmojiEntry("🛺", "auto rickshaw tuktuk"),
        EmojiEntry("🚲", "bicycle bike"),
        EmojiEntry("🛴", "kick scooter"),
        EmojiEntry("🚏", "bus stop"),
        EmojiEntry("🛞", "wheel"),
        EmojiEntry("🚨", "rotating light emergency siren"),
        EmojiEntry("🚥", "horizontal traffic light"),
        EmojiEntry("🚦", "vertical traffic light"),
        EmojiEntry("🛑", "stop sign"),
        EmojiEntry("🚧", "construction barrier"),
        EmojiEntry("⚓", "anchor ship"),
        EmojiEntry("⛵", "sailboat"),
        EmojiEntry("🛶", "canoe kayak"),
        EmojiEntry("🚤", "speedboat"),
        EmojiEntry("🛳️", "passenger ship cruise"),
        EmojiEntry("⛴️", "ferry"),
        EmojiEntry("🛥️", "motor boat"),
        EmojiEntry("🚢", "ship"),
    )),
    EmojiCategory("Objects", "💻", listOf(
        EmojiEntry("⌚", "watch wristwatch"),
        EmojiEntry("📱", "phone mobile cell"),
        EmojiEntry("📲", "mobile phone arrow"),
        EmojiEntry("💻", "laptop computer"),
        EmojiEntry("⌨️", "keyboard typing"),
        EmojiEntry("🖥️", "desktop computer screen"),
        EmojiEntry("🖨️", "printer"),
        EmojiEntry("🖱️", "computer mouse"),
        EmojiEntry("🖲️", "trackball"),
        EmojiEntry("🗜️", "clamp"),
        EmojiEntry("💽", "computer disk minidisc"),
        EmojiEntry("💾", "floppy disk save"),
        EmojiEntry("💿", "cd disc optical"),
        EmojiEntry("📀", "dvd"),
        EmojiEntry("📼", "videocassette vhs tape"),
        EmojiEntry("📷", "camera photo"),
        EmojiEntry("📸", "camera with flash photo"),
        EmojiEntry("📹", "video camera"),
        EmojiEntry("🎥", "movie camera film"),
        EmojiEntry("📽️", "film projector"),
        EmojiEntry("📺", "television tv"),
        EmojiEntry("📻", "radio"),
        EmojiEntry("📞", "telephone receiver"),
        EmojiEntry("☎️", "phone telephone"),
        EmojiEntry("📟", "pager"),
        EmojiEntry("📠", "fax machine"),
        EmojiEntry("🔋", "battery"),
        EmojiEntry("🪫", "low battery"),
        EmojiEntry("🔌", "electric plug"),
        EmojiEntry("💡", "light bulb idea"),
        EmojiEntry("🔦", "flashlight torch"),
        EmojiEntry("🕯️", "candle"),
        EmojiEntry("🪔", "diya oil lamp"),
        EmojiEntry("🧯", "fire extinguisher"),
        EmojiEntry("🛢️", "oil drum"),
        EmojiEntry("💸", "money with wings flying"),
        EmojiEntry("💵", "dollar banknote"),
        EmojiEntry("💴", "yen banknote"),
        EmojiEntry("💶", "euro banknote"),
        EmojiEntry("💷", "pound banknote"),
        EmojiEntry("💰", "money bag cash"),
        EmojiEntry("🪙", "coin"),
        EmojiEntry("💳", "credit card"),
        EmojiEntry("🧾", "receipt invoice"),
        EmojiEntry("💎", "gem stone diamond"),
        EmojiEntry("⚖️", "balance scale justice"),
        EmojiEntry("🪜", "ladder"),
        EmojiEntry("🧰", "toolbox"),
        EmojiEntry("🪛", "screwdriver"),
        EmojiEntry("🔧", "wrench tool fix"),
        EmojiEntry("🔨", "hammer tool build"),
        EmojiEntry("⚒️", "hammer and pick"),
        EmojiEntry("🛠️", "hammer wrench tools"),
        EmojiEntry("⛏️", "pick mining"),
        EmojiEntry("🪚", "carpentry saw"),
        EmojiEntry("🔩", "nut and bolt"),
        EmojiEntry("⚙️", "gear settings cog"),
        EmojiEntry("🪤", "mouse trap"),
        EmojiEntry("🧱", "brick"),
        EmojiEntry("⛓️", "chains"),
        EmojiEntry("🧲", "magnet attract"),
        EmojiEntry("🔫", "water gun toy"),
        EmojiEntry("💣", "bomb"),
        EmojiEntry("🧨", "firecracker"),
        EmojiEntry("🪓", "axe"),
        EmojiEntry("🔪", "kitchen knife cooking"),
        EmojiEntry("🗡️", "dagger blade"),
        EmojiEntry("⚔️", "crossed swords battle"),
        EmojiEntry("🛡️", "shield protection"),
        EmojiEntry("🚬", "cigarette smoking"),
        EmojiEntry("⚰️", "coffin"),
        EmojiEntry("🪦", "headstone grave"),
        EmojiEntry("⚱️", "funeral urn"),
        EmojiEntry("🗿", "moai statue"),
        EmojiEntry("🪧", "placard sign protest"),
        EmojiEntry("🪪", "id card identification"),
        EmojiEntry("🩸", "drop of blood"),
        EmojiEntry("💉", "syringe injection"),
        EmojiEntry("🩹", "adhesive bandage"),
        EmojiEntry("🩺", "stethoscope"),
        EmojiEntry("💊", "pill medicine"),
        EmojiEntry("🧬", "dna"),
        EmojiEntry("🧫", "petri dish"),
        EmojiEntry("🧪", "test tube science"),
        EmojiEntry("🌡️", "thermometer"),
        EmojiEntry("🧹", "broom"),
        EmojiEntry("🧺", "basket"),
        EmojiEntry("🧻", "roll paper toilet"),
        EmojiEntry("🚽", "toilet"),
        EmojiEntry("🪠", "plunger"),
        EmojiEntry("🚰", "potable water"),
        EmojiEntry("🚿", "shower"),
        EmojiEntry("🛁", "bathtub"),
        EmojiEntry("🧼", "soap"),
        EmojiEntry("🪥", "toothbrush"),
        EmojiEntry("🪒", "razor"),
        EmojiEntry("🧴", "lotion bottle"),
        EmojiEntry("🧷", "safety pin"),
        EmojiEntry("🧽", "sponge"),
        EmojiEntry("🪣", "bucket"),
        EmojiEntry("🛒", "shopping cart"),
        EmojiEntry("🛍️", "shopping bags"),
        EmojiEntry("🎁", "wrapped gift present"),
        EmojiEntry("🎀", "ribbon bow"),
        EmojiEntry("🪄", "magic wand"),
        EmojiEntry("🧿", "nazar amulet evil eye"),
        EmojiEntry("🔮", "crystal ball fortune"),
        EmojiEntry("🎈", "balloon"),
        EmojiEntry("🎉", "party popper celebration"),
        EmojiEntry("🎊", "confetti ball party"),
        EmojiEntry("🎏", "carp streamer japanese"),
        EmojiEntry("🎐", "wind chime japanese"),
        EmojiEntry("🎎", "japanese dolls"),
        EmojiEntry("🎍", "pine decoration kadomatsu"),
        EmojiEntry("🎋", "tanabata tree wish"),
        EmojiEntry("🪞", "mirror"),
        EmojiEntry("🪟", "window"),
        EmojiEntry("🛏️", "bed"),
        EmojiEntry("🛋️", "couch lamp sofa"),
        EmojiEntry("🪑", "chair"),
        EmojiEntry("🚪", "door"),
        EmojiEntry("🖼️", "framed picture art"),
        EmojiEntry("🪆", "nesting dolls matryoshka"),
        EmojiEntry("📦", "package box"),
        EmojiEntry("📭", "mailbox flag down"),
        EmojiEntry("📬", "mailbox flag up"),
        EmojiEntry("📫", "closed mailbox flag up"),
        EmojiEntry("📪", "closed mailbox flag down"),
        EmojiEntry("📮", "postbox"),
        EmojiEntry("📯", "postal horn"),
        EmojiEntry("📜", "scroll"),
        EmojiEntry("📃", "page curl"),
        EmojiEntry("📄", "page facing up"),
        EmojiEntry("📑", "bookmark tabs"),
        EmojiEntry("📊", "bar chart graph stats"),
        EmojiEntry("📈", "chart trending up"),
        EmojiEntry("📉", "chart trending down"),
        EmojiEntry("📅", "calendar date"),
        EmojiEntry("📆", "tear off calendar"),
        EmojiEntry("🗓️", "spiral calendar"),
        EmojiEntry("📇", "card index rolodex"),
        EmojiEntry("🗃️", "card file box"),
        EmojiEntry("🗳️", "ballot box vote"),
        EmojiEntry("🗄️", "file cabinet"),
        EmojiEntry("📋", "clipboard"),
        EmojiEntry("📁", "file folder"),
        EmojiEntry("📂", "open file folder"),
        EmojiEntry("🗂️", "card index dividers"),
        EmojiEntry("🗞️", "rolled up newspaper"),
        EmojiEntry("📰", "newspaper"),
        EmojiEntry("📓", "notebook"),
        EmojiEntry("📔", "decorated notebook"),
        EmojiEntry("📒", "ledger"),
        EmojiEntry("📕", "closed book red"),
        EmojiEntry("📗", "green book"),
        EmojiEntry("📘", "blue book"),
        EmojiEntry("📙", "orange book"),
        EmojiEntry("📚", "books library stack"),
        EmojiEntry("📖", "open book reading"),
        EmojiEntry("🔖", "bookmark"),
        EmojiEntry("🔗", "link chain url"),
        EmojiEntry("📎", "paperclip"),
        EmojiEntry("🖇️", "linked paperclips"),
        EmojiEntry("📐", "triangular ruler"),
        EmojiEntry("📏", "straight ruler"),
        EmojiEntry("✂️", "scissors cut"),
        EmojiEntry("🖊️", "pen"),
        EmojiEntry("🖋️", "fountain pen"),
        EmojiEntry("✒️", "black nib pen"),
        EmojiEntry("🖌️", "paintbrush"),
        EmojiEntry("🖍️", "crayon"),
        EmojiEntry("📝", "memo note write"),
        EmojiEntry("✏️", "pencil write edit"),
        EmojiEntry("🔍", "magnifying glass search left"),
        EmojiEntry("🔎", "magnifying glass search right"),
        EmojiEntry("🔬", "microscope science lab"),
        EmojiEntry("🔭", "telescope astronomy"),
        EmojiEntry("📡", "satellite antenna"),
        EmojiEntry("🔑", "key"),
        EmojiEntry("🗝️", "old key"),
        EmojiEntry("🔐", "lock with key"),
        EmojiEntry("🔒", "lock locked"),
        EmojiEntry("🔓", "unlock unlocked"),
        EmojiEntry("🔏", "lock with pen"),
        EmojiEntry("🪝", "hook"),
        EmojiEntry("📧", "email mail at"),
        EmojiEntry("📨", "incoming envelope"),
        EmojiEntry("📩", "envelope arrow"),
        EmojiEntry("📤", "outbox tray"),
        EmojiEntry("📥", "inbox tray"),
        EmojiEntry("✉️", "envelope letter"),
        EmojiEntry("👓", "glasses"),
        EmojiEntry("🕶️", "dark sunglasses"),
        EmojiEntry("🥽", "goggles"),
        EmojiEntry("🥼", "lab coat"),
        EmojiEntry("🦺", "safety vest"),
        EmojiEntry("👔", "necktie"),
        EmojiEntry("👕", "t shirt"),
        EmojiEntry("👖", "jeans"),
        EmojiEntry("🧣", "scarf"),
        EmojiEntry("🧤", "gloves"),
        EmojiEntry("🧥", "coat"),
        EmojiEntry("🧦", "socks"),
        EmojiEntry("👗", "dress"),
        EmojiEntry("👘", "kimono"),
        EmojiEntry("🥻", "sari"),
        EmojiEntry("🩱", "one piece swimsuit"),
        EmojiEntry("🩲", "briefs underwear"),
        EmojiEntry("🩳", "shorts"),
        EmojiEntry("👙", "bikini"),
        EmojiEntry("👚", "blouse"),
        EmojiEntry("👛", "purse"),
        EmojiEntry("👜", "handbag"),
        EmojiEntry("👝", "clutch bag pouch"),
        EmojiEntry("🎒", "backpack school bag"),
        EmojiEntry("🩴", "thong sandal flip flop"),
        EmojiEntry("👞", "mans shoe"),
        EmojiEntry("👟", "running shoe sneaker"),
        EmojiEntry("🥾", "hiking boot"),
        EmojiEntry("🥿", "flat shoe"),
        EmojiEntry("👠", "high heel"),
        EmojiEntry("👡", "womans sandal"),
        EmojiEntry("👢", "womans boot"),
        EmojiEntry("👑", "crown royal"),
        EmojiEntry("👒", "womans hat"),
        EmojiEntry("🎩", "top hat"),
        EmojiEntry("🎓", "graduation cap mortarboard"),
        EmojiEntry("🧢", "billed cap baseball"),
        EmojiEntry("🪖", "military helmet"),
        EmojiEntry("⛑️", "rescue helmet"),
        EmojiEntry("📿", "prayer beads"),
        EmojiEntry("💄", "lipstick"),
        EmojiEntry("💍", "ring engagement"),
        EmojiEntry("⏰", "alarm clock"),
        EmojiEntry("⏱️", "stopwatch"),
        EmojiEntry("⏲️", "timer clock"),
        EmojiEntry("🕰️", "mantelpiece clock"),
        EmojiEntry("⌛", "hourglass done"),
        EmojiEntry("⏳", "hourglass not done flowing"),
        EmojiEntry("🧸", "teddy bear plush"),
        EmojiEntry("🎯", "bullseye target dart"),
    )),
    EmojiCategory("Symbols", "⭐", listOf(
        EmojiEntry("❤️", "red heart love"),
        EmojiEntry("🧡", "orange heart"),
        EmojiEntry("💛", "yellow heart"),
        EmojiEntry("💚", "green heart"),
        EmojiEntry("💙", "blue heart"),
        EmojiEntry("💜", "purple heart"),
        EmojiEntry("🤎", "brown heart"),
        EmojiEntry("🖤", "black heart"),
        EmojiEntry("🤍", "white heart"),
        EmojiEntry("💔", "broken heart"),
        EmojiEntry("❣️", "heart exclamation"),
        EmojiEntry("💕", "two hearts"),
        EmojiEntry("💞", "revolving hearts"),
        EmojiEntry("💓", "beating heart"),
        EmojiEntry("💗", "growing heart"),
        EmojiEntry("💖", "sparkling heart"),
        EmojiEntry("💘", "heart arrow cupid"),
        EmojiEntry("💝", "heart ribbon gift"),
        EmojiEntry("💟", "heart decoration"),
        EmojiEntry("💋", "kiss mark lipstick"),
        EmojiEntry("💌", "love letter"),
        EmojiEntry("☮️", "peace symbol"),
        EmojiEntry("✝️", "latin cross christianity"),
        EmojiEntry("☪️", "star and crescent islam"),
        EmojiEntry("🕉️", "om hinduism"),
        EmojiEntry("☸️", "wheel of dharma buddhism"),
        EmojiEntry("✡️", "star of david judaism"),
        EmojiEntry("🔯", "six pointed star dotted"),
        EmojiEntry("🕎", "menorah"),
        EmojiEntry("☯️", "yin yang"),
        EmojiEntry("☦️", "orthodox cross"),
        EmojiEntry("🛐", "place of worship"),
        EmojiEntry("⛎", "ophiuchus"),
        EmojiEntry("♈", "aries zodiac ram"),
        EmojiEntry("♉", "taurus zodiac bull"),
        EmojiEntry("♊", "gemini zodiac twins"),
        EmojiEntry("♋", "cancer zodiac crab"),
        EmojiEntry("♌", "leo zodiac lion"),
        EmojiEntry("♍", "virgo zodiac"),
        EmojiEntry("♎", "libra zodiac scales"),
        EmojiEntry("♏", "scorpio zodiac"),
        EmojiEntry("♐", "sagittarius zodiac archer"),
        EmojiEntry("♑", "capricorn zodiac goat"),
        EmojiEntry("♒", "aquarius zodiac"),
        EmojiEntry("♓", "pisces zodiac fish"),
        EmojiEntry("🆔", "id button"),
        EmojiEntry("⚛️", "atom symbol science"),
        EmojiEntry("☢️", "radioactive"),
        EmojiEntry("☣️", "biohazard"),
        EmojiEntry("📴", "mobile phone off"),
        EmojiEntry("📳", "vibration mode"),
        EmojiEntry("🆘", "sos help"),
        EmojiEntry("❌", "cross mark x wrong"),
        EmojiEntry("⭕", "hollow red circle"),
        EmojiEntry("⛔", "no entry"),
        EmojiEntry("📛", "name badge"),
        EmojiEntry("🚫", "prohibited"),
        EmojiEntry("💯", "hundred perfect score"),
        EmojiEntry("💢", "anger symbol vein"),
        EmojiEntry("♨️", "hot springs"),
        EmojiEntry("🚷", "no pedestrians"),
        EmojiEntry("🚯", "no littering"),
        EmojiEntry("🚳", "no bicycles"),
        EmojiEntry("🚱", "non potable water"),
        EmojiEntry("🔞", "no one under 18"),
        EmojiEntry("📵", "no mobile phones"),
        EmojiEntry("🚭", "no smoking"),
        EmojiEntry("❗", "exclamation important"),
        EmojiEntry("❕", "white exclamation"),
        EmojiEntry("❓", "question"),
        EmojiEntry("❔", "white question"),
        EmojiEntry("‼️", "double exclamation"),
        EmojiEntry("⁉️", "interrobang exclamation question"),
        EmojiEntry("🔅", "dim button low brightness"),
        EmojiEntry("🔆", "bright button"),
        EmojiEntry("⚠️", "warning caution"),
        EmojiEntry("🚸", "children crossing"),
        EmojiEntry("🔱", "trident"),
        EmojiEntry("⚜️", "fleur de lis"),
        EmojiEntry("🔰", "japanese symbol for beginner"),
        EmojiEntry("♻️", "recycle"),
        EmojiEntry("✅", "check mark green done"),
        EmojiEntry("💹", "chart yen increasing"),
        EmojiEntry("❇️", "sparkle"),
        EmojiEntry("✳️", "eight spoked asterisk"),
        EmojiEntry("✴️", "eight pointed star"),
        EmojiEntry("❎", "cross mark button"),
        EmojiEntry("🌐", "globe with meridians"),
        EmojiEntry("💠", "diamond with dot"),
        EmojiEntry("🌀", "cyclone spiral"),
        EmojiEntry("💤", "zzz sleep"),
        EmojiEntry("🏧", "atm sign"),
        EmojiEntry("🚾", "water closet wc"),
        EmojiEntry("♿", "wheelchair accessible"),
        EmojiEntry("🅿️", "p button parking"),
        EmojiEntry("🛗", "elevator"),
        EmojiEntry("🛂", "passport control"),
        EmojiEntry("🛃", "customs"),
        EmojiEntry("🛄", "baggage claim"),
        EmojiEntry("🛅", "left luggage"),
        EmojiEntry("🚹", "mens room"),
        EmojiEntry("🚺", "womens room"),
        EmojiEntry("🚼", "baby symbol"),
        EmojiEntry("🚻", "restroom"),
        EmojiEntry("🚮", "litter in bin"),
        EmojiEntry("🎦", "cinema"),
        EmojiEntry("📶", "antenna bars signal"),
        EmojiEntry("🔣", "input symbols"),
        EmojiEntry("ℹ️", "information"),
        EmojiEntry("🔤", "input latin letters"),
        EmojiEntry("🔡", "input latin lowercase"),
        EmojiEntry("🔠", "input latin uppercase"),
        EmojiEntry("🆖", "ng button no good"),
        EmojiEntry("🆗", "ok button"),
        EmojiEntry("🆙", "up button"),
        EmojiEntry("🆒", "cool button"),
        EmojiEntry("🆕", "new button"),
        EmojiEntry("🆓", "free button"),
        EmojiEntry("0️⃣", "keycap 0 zero"),
        EmojiEntry("1️⃣", "keycap 1 one"),
        EmojiEntry("2️⃣", "keycap 2 two"),
        EmojiEntry("3️⃣", "keycap 3 three"),
        EmojiEntry("4️⃣", "keycap 4 four"),
        EmojiEntry("5️⃣", "keycap 5 five"),
        EmojiEntry("6️⃣", "keycap 6 six"),
        EmojiEntry("7️⃣", "keycap 7 seven"),
        EmojiEntry("8️⃣", "keycap 8 eight"),
        EmojiEntry("9️⃣", "keycap 9 nine"),
        EmojiEntry("🔟", "keycap 10 ten"),
        EmojiEntry("🔢", "input numbers"),
        EmojiEntry("#️⃣", "keycap hash pound"),
        EmojiEntry("*️⃣", "keycap asterisk star"),
        EmojiEntry("⏏️", "eject button"),
        EmojiEntry("▶️", "play button"),
        EmojiEntry("⏸️", "pause button"),
        EmojiEntry("⏯️", "play or pause button"),
        EmojiEntry("⏹️", "stop button"),
        EmojiEntry("⏺️", "record button"),
        EmojiEntry("⏭️", "next track"),
        EmojiEntry("⏮️", "previous track"),
        EmojiEntry("⏩", "fast forward"),
        EmojiEntry("⏪", "fast reverse rewind"),
        EmojiEntry("⏫", "fast up"),
        EmojiEntry("⏬", "fast down"),
        EmojiEntry("◀️", "reverse left"),
        EmojiEntry("🔼", "upwards button"),
        EmojiEntry("🔽", "downwards button"),
        EmojiEntry("➡️", "right arrow"),
        EmojiEntry("⬅️", "left arrow"),
        EmojiEntry("⬆️", "up arrow"),
        EmojiEntry("⬇️", "down arrow"),
        EmojiEntry("↗️", "up right arrow"),
        EmojiEntry("↘️", "down right arrow"),
        EmojiEntry("↙️", "down left arrow"),
        EmojiEntry("↖️", "up left arrow"),
        EmojiEntry("↕️", "up down arrow"),
        EmojiEntry("↔️", "left right arrow"),
        EmojiEntry("↪️", "left arrow curving right"),
        EmojiEntry("↩️", "right arrow curving left"),
        EmojiEntry("⤴️", "right arrow curving up"),
        EmojiEntry("⤵️", "right arrow curving down"),
        EmojiEntry("🔃", "clockwise vertical arrows reload"),
        EmojiEntry("🔄", "counterclockwise arrows refresh"),
        EmojiEntry("🔙", "back arrow"),
        EmojiEntry("🔚", "end arrow"),
        EmojiEntry("🔛", "on arrow"),
        EmojiEntry("🔜", "soon arrow"),
        EmojiEntry("🔝", "top arrow"),
        EmojiEntry("➕", "plus add"),
        EmojiEntry("➖", "minus subtract"),
        EmojiEntry("➗", "divide division"),
        EmojiEntry("✖️", "multiply x"),
        EmojiEntry("🟰", "heavy equals"),
        EmojiEntry("♾️", "infinity forever"),
        EmojiEntry("〰️", "wavy dash"),
        EmojiEntry("©️", "copyright"),
        EmojiEntry("®️", "registered"),
        EmojiEntry("™️", "trade mark"),
        EmojiEntry("⭐", "star"),
        EmojiEntry("🌟", "glowing star shiny"),
        EmojiEntry("✨", "sparkles glitter"),
        EmojiEntry("💫", "dizzy star"),
        EmojiEntry("⚡", "lightning bolt zap electric"),
        EmojiEntry("🔥", "fire hot flame lit"),
        EmojiEntry("🌈", "rainbow"),
        EmojiEntry("☀️", "sun sunny"),
        EmojiEntry("🌤️", "sun behind small cloud"),
        EmojiEntry("⛅", "sun behind cloud partly"),
        EmojiEntry("🌥️", "sun behind large cloud"),
        EmojiEntry("☁️", "cloud cloudy"),
        EmojiEntry("🌦️", "sun behind rain cloud"),
        EmojiEntry("🌧️", "cloud rain rainy"),
        EmojiEntry("⛈️", "thunder cloud rain storm"),
        EmojiEntry("🌩️", "cloud lightning"),
        EmojiEntry("🌨️", "cloud snow"),
        EmojiEntry("❄️", "snowflake snow"),
        EmojiEntry("☃️", "snowman snow"),
        EmojiEntry("⛄", "snowman without snow"),
        EmojiEntry("🌬️", "wind face blowing"),
        EmojiEntry("💨", "dash speed"),
        EmojiEntry("🌪️", "tornado"),
        EmojiEntry("🌫️", "fog mist"),
        EmojiEntry("☔", "umbrella with rain drops"),
        EmojiEntry("☂️", "umbrella closed"),
        EmojiEntry("💧", "droplet water drop"),
        EmojiEntry("🌊", "wave ocean water"),
        EmojiEntry("🌙", "crescent moon night"),
        EmojiEntry("🌚", "new moon face"),
        EmojiEntry("🌛", "first quarter moon face"),
        EmojiEntry("🌜", "last quarter moon face"),
        EmojiEntry("🌝", "full moon face"),
        EmojiEntry("🌞", "sun with face"),
        EmojiEntry("🌑", "new moon"),
        EmojiEntry("🌒", "waxing crescent moon"),
        EmojiEntry("🌓", "first quarter moon"),
        EmojiEntry("🌔", "waxing gibbous moon"),
        EmojiEntry("🌕", "full moon"),
        EmojiEntry("🌖", "waning gibbous moon"),
        EmojiEntry("🌗", "last quarter moon"),
        EmojiEntry("🌘", "waning crescent moon"),
        EmojiEntry("🪐", "ringed planet saturn"),
        EmojiEntry("🔴", "red circle"),
        EmojiEntry("🟠", "orange circle"),
        EmojiEntry("🟡", "yellow circle"),
        EmojiEntry("🟢", "green circle"),
        EmojiEntry("🔵", "blue circle"),
        EmojiEntry("🟣", "purple circle"),
        EmojiEntry("🟤", "brown circle"),
        EmojiEntry("⚫", "black circle"),
        EmojiEntry("⚪", "white circle"),
        EmojiEntry("🟥", "red square"),
        EmojiEntry("🟧", "orange square"),
        EmojiEntry("🟨", "yellow square"),
        EmojiEntry("🟩", "green square"),
        EmojiEntry("🟦", "blue square"),
        EmojiEntry("🟪", "purple square"),
        EmojiEntry("🟫", "brown square"),
        EmojiEntry("⬛", "black large square"),
        EmojiEntry("⬜", "white large square"),
        EmojiEntry("🔶", "large orange diamond"),
        EmojiEntry("🔷", "large blue diamond"),
        EmojiEntry("🔸", "small orange diamond"),
        EmojiEntry("🔹", "small blue diamond"),
        EmojiEntry("🔺", "red triangle pointed up"),
        EmojiEntry("🔻", "red triangle pointed down"),
        EmojiEntry("🔘", "radio button"),
        EmojiEntry("🔳", "white square button"),
        EmojiEntry("🔲", "black square button"),
        EmojiEntry("🏷️", "label tag"),
    )),
    EmojiCategory("Flags", "🏁", listOf(
        EmojiEntry("🏳️", "white flag surrender"),
        EmojiEntry("🏴", "black flag"),
        EmojiEntry("🏳️‍🌈", "rainbow flag pride lgbt"),
        EmojiEntry("🏳️‍⚧️", "transgender flag"),
        EmojiEntry("🏴‍☠️", "pirate flag jolly roger skull"),
        EmojiEntry("🚩", "triangular flag post"),
        EmojiEntry("🎌", "crossed flags japanese"),
        EmojiEntry("🏁", "checkered flag finish race"),
        EmojiEntry("🇺🇸", "flag us usa america united states"),
        EmojiEntry("🇬🇧", "flag gb uk britain england"),
        EmojiEntry("🇨🇦", "flag ca canada"),
        EmojiEntry("🇯🇵", "flag jp japan"),
        EmojiEntry("🇨🇳", "flag cn china"),
        EmojiEntry("🇰🇷", "flag kr korea south"),
        EmojiEntry("🇰🇵", "flag kp korea north"),
        EmojiEntry("🇩🇪", "flag de germany"),
        EmojiEntry("🇫🇷", "flag fr france"),
        EmojiEntry("🇮🇹", "flag it italy"),
        EmojiEntry("🇪🇸", "flag es spain"),
        EmojiEntry("🇵🇹", "flag pt portugal"),
        EmojiEntry("🇳🇱", "flag nl netherlands"),
        EmojiEntry("🇧🇪", "flag be belgium"),
        EmojiEntry("🇨🇭", "flag ch switzerland"),
        EmojiEntry("🇦🇹", "flag at austria"),
        EmojiEntry("🇸🇪", "flag se sweden"),
        EmojiEntry("🇳🇴", "flag no norway"),
        EmojiEntry("🇩🇰", "flag dk denmark"),
        EmojiEntry("🇫🇮", "flag fi finland"),
        EmojiEntry("🇮🇸", "flag is iceland"),
        EmojiEntry("🇮🇪", "flag ie ireland"),
        EmojiEntry("🇵🇱", "flag pl poland"),
        EmojiEntry("🇨🇿", "flag cz czechia czech republic"),
        EmojiEntry("🇸🇰", "flag sk slovakia"),
        EmojiEntry("🇭🇺", "flag hu hungary"),
        EmojiEntry("🇷🇴", "flag ro romania"),
        EmojiEntry("🇬🇷", "flag gr greece"),
        EmojiEntry("🇹🇷", "flag tr turkey"),
        EmojiEntry("🇷🇺", "flag ru russia"),
        EmojiEntry("🇺🇦", "flag ua ukraine"),
        EmojiEntry("🇧🇾", "flag by belarus"),
        EmojiEntry("🇮🇳", "flag in india"),
        EmojiEntry("🇵🇰", "flag pk pakistan"),
        EmojiEntry("🇧🇩", "flag bd bangladesh"),
        EmojiEntry("🇱🇰", "flag lk sri lanka"),
        EmojiEntry("🇳🇵", "flag np nepal"),
        EmojiEntry("🇹🇭", "flag th thailand"),
        EmojiEntry("🇻🇳", "flag vn vietnam"),
        EmojiEntry("🇵🇭", "flag ph philippines"),
        EmojiEntry("🇮🇩", "flag id indonesia"),
        EmojiEntry("🇲🇾", "flag my malaysia"),
        EmojiEntry("🇸🇬", "flag sg singapore"),
        EmojiEntry("🇦🇺", "flag au australia"),
        EmojiEntry("🇳🇿", "flag nz new zealand"),
        EmojiEntry("🇲🇽", "flag mx mexico"),
        EmojiEntry("🇧🇷", "flag br brazil"),
        EmojiEntry("🇦🇷", "flag ar argentina"),
        EmojiEntry("🇨🇱", "flag cl chile"),
        EmojiEntry("🇨🇴", "flag co colombia"),
        EmojiEntry("🇵🇪", "flag pe peru"),
        EmojiEntry("🇻🇪", "flag ve venezuela"),
        EmojiEntry("🇺🇾", "flag uy uruguay"),
        EmojiEntry("🇨🇺", "flag cu cuba"),
        EmojiEntry("🇪🇬", "flag eg egypt"),
        EmojiEntry("🇿🇦", "flag za south africa"),
        EmojiEntry("🇳🇬", "flag ng nigeria"),
        EmojiEntry("🇰🇪", "flag ke kenya"),
        EmojiEntry("🇪🇹", "flag et ethiopia"),
        EmojiEntry("🇲🇦", "flag ma morocco"),
        EmojiEntry("🇩🇿", "flag dz algeria"),
        EmojiEntry("🇮🇱", "flag il israel"),
        EmojiEntry("🇸🇦", "flag sa saudi arabia"),
        EmojiEntry("🇦🇪", "flag ae united arab emirates uae"),
        EmojiEntry("🇮🇷", "flag ir iran"),
        EmojiEntry("🇮🇶", "flag iq iraq"),
        EmojiEntry("🇸🇾", "flag sy syria"),
        EmojiEntry("🇱🇧", "flag lb lebanon"),
        EmojiEntry("🇯🇴", "flag jo jordan"),
        EmojiEntry("🇵🇸", "flag ps palestine"),
        EmojiEntry("🇦🇫", "flag af afghanistan"),
        EmojiEntry("🇪🇺", "flag eu european union"),
        EmojiEntry("🇺🇳", "flag un united nations"),
    )),
)
