// GENERATED by scripts/generate.ts from src/map.json — DO NOT EDIT.
// Regenerate with: pnpm --filter @marmalade/icons generate

/** Which upstream license covers a glyph. Lucide's LICENSE is a DUAL license:
 *  ISC for Lucide originals, MIT (© Cole Bemis) for the icons it lists as
 *  derived from Feather. See LICENSE.lucide and the repo THIRD-PARTY-NOTICES.md. */
export type IconLicense = "isc" | "mit-feather";

export interface IconEntry {
  /** Upstream Lucide glyph name. */
  readonly glyph: string;
  readonly license: IconLicense;
  /** Inner SVG markup, to be wrapped in the shared 24x24 shell (see SVG_ATTRS). */
  readonly svg: string;
  /** The same drawing, parsed — so a renderer can build real elements instead
   *  of injecting markup. Attribute names are SVG-native and dash-free, so they
   *  pass straight through to React/JSX. */
  readonly shapes: readonly { readonly tag: string; readonly attrs: Readonly<Record<string, string>> }[];
}

export const ICONS = {
  "icon.tool.terminal": { glyph: "square-terminal", license: "isc", svg: "<path d=\"m7 11 2-2-2-2\" /> <path d=\"M11 13h4\" /> <rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" />",
    shapes: [{"tag":"path","attrs":{"d":"m7 11 2-2-2-2"}},{"tag":"path","attrs":{"d":"M11 13h4"}},{"tag":"rect","attrs":{"width":"18","height":"18","x":"3","y":"3","rx":"2","ry":"2"}}] },
  "icon.tool.read": { glyph: "file-text", license: "isc", svg: "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /> <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /> <path d=\"M10 9H8\" /> <path d=\"M16 13H8\" /> <path d=\"M16 17H8\" />",
    shapes: [{"tag":"path","attrs":{"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}},{"tag":"path","attrs":{"d":"M14 2v5a1 1 0 0 0 1 1h5"}},{"tag":"path","attrs":{"d":"M10 9H8"}},{"tag":"path","attrs":{"d":"M16 13H8"}},{"tag":"path","attrs":{"d":"M16 17H8"}}] },
  "icon.tool.write": { glyph: "file-plus", license: "isc", svg: "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /> <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /> <path d=\"M9 15h6\" /> <path d=\"M12 18v-6\" />",
    shapes: [{"tag":"path","attrs":{"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}},{"tag":"path","attrs":{"d":"M14 2v5a1 1 0 0 0 1 1h5"}},{"tag":"path","attrs":{"d":"M9 15h6"}},{"tag":"path","attrs":{"d":"M12 18v-6"}}] },
  "icon.tool.edit": { glyph: "file-pen", license: "isc", svg: "<path d=\"M12.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v9.34\" /> <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /> <path d=\"M10.378 12.622a1 1 0 0 1 3 3.003L8.36 20.637a2 2 0 0 1-.854.506l-2.867.837a.5.5 0 0 1-.62-.62l.836-2.869a2 2 0 0 1 .506-.853z\" />",
    shapes: [{"tag":"path","attrs":{"d":"M12.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v9.34"}},{"tag":"path","attrs":{"d":"M14 2v5a1 1 0 0 0 1 1h5"}},{"tag":"path","attrs":{"d":"M10.378 12.622a1 1 0 0 1 3 3.003L8.36 20.637a2 2 0 0 1-.854.506l-2.867.837a.5.5 0 0 1-.62-.62l.836-2.869a2 2 0 0 1 .506-.853z"}}] },
  "icon.tool.list": { glyph: "folder-open", license: "isc", svg: "<path d=\"m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2\" />",
    shapes: [{"tag":"path","attrs":{"d":"m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"}}] },
  "icon.tool.search": { glyph: "search-code", license: "isc", svg: "<path d=\"m13 13.5 2-2.5-2-2.5\" /> <path d=\"m21 21-4.3-4.3\" /> <path d=\"M9 8.5 7 11l2 2.5\" /> <circle cx=\"11\" cy=\"11\" r=\"8\" />",
    shapes: [{"tag":"path","attrs":{"d":"m13 13.5 2-2.5-2-2.5"}},{"tag":"path","attrs":{"d":"m21 21-4.3-4.3"}},{"tag":"path","attrs":{"d":"M9 8.5 7 11l2 2.5"}},{"tag":"circle","attrs":{"cx":"11","cy":"11","r":"8"}}] },
  "icon.tool.web.fetch": { glyph: "globe", license: "isc", svg: "<circle cx=\"12\" cy=\"12\" r=\"10\" /> <path d=\"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20\" /> <path d=\"M2 12h20\" />",
    shapes: [{"tag":"circle","attrs":{"cx":"12","cy":"12","r":"10"}},{"tag":"path","attrs":{"d":"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"}},{"tag":"path","attrs":{"d":"M2 12h20"}}] },
  "icon.tool.web.search": { glyph: "search", license: "mit-feather", svg: "<path d=\"m21 21-4.34-4.34\" /> <circle cx=\"11\" cy=\"11\" r=\"8\" />",
    shapes: [{"tag":"path","attrs":{"d":"m21 21-4.34-4.34"}},{"tag":"circle","attrs":{"cx":"11","cy":"11","r":"8"}}] },
  "icon.tool.image": { glyph: "image", license: "isc", svg: "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" /> <circle cx=\"9\" cy=\"9\" r=\"2\" /> <path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\" />",
    shapes: [{"tag":"rect","attrs":{"width":"18","height":"18","x":"3","y":"3","rx":"2","ry":"2"}},{"tag":"circle","attrs":{"cx":"9","cy":"9","r":"2"}},{"tag":"path","attrs":{"d":"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}}] },
  "icon.tool.skill": { glyph: "feather", license: "mit-feather", svg: "<path d=\"M14.086 18.412A2 2 0 0112.67 19H5v-7.672a2 2 0 01.586-1.414L11.75 3.75a6 6 0 118.49 8.49z\" /> <path d=\"M16 8 2 22\" /> <path d=\"M17.488 15H9\" />",
    shapes: [{"tag":"path","attrs":{"d":"M14.086 18.412A2 2 0 0112.67 19H5v-7.672a2 2 0 01.586-1.414L11.75 3.75a6 6 0 118.49 8.49z"}},{"tag":"path","attrs":{"d":"M16 8 2 22"}},{"tag":"path","attrs":{"d":"M17.488 15H9"}}] },
  "icon.tool.subagent": { glyph: "bot", license: "isc", svg: "<path d=\"M12 8V4H8\" /> <rect width=\"16\" height=\"12\" x=\"4\" y=\"8\" rx=\"2\" /> <path d=\"M2 14h2\" /> <path d=\"M20 14h2\" /> <path d=\"M15 13v2\" /> <path d=\"M9 13v2\" />",
    shapes: [{"tag":"path","attrs":{"d":"M12 8V4H8"}},{"tag":"rect","attrs":{"width":"16","height":"12","x":"4","y":"8","rx":"2"}},{"tag":"path","attrs":{"d":"M2 14h2"}},{"tag":"path","attrs":{"d":"M20 14h2"}},{"tag":"path","attrs":{"d":"M15 13v2"}},{"tag":"path","attrs":{"d":"M9 13v2"}}] },
  "icon.tool.question": { glyph: "message-circle-question-mark", license: "isc", svg: "<path d=\"M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719\" /> <path d=\"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3\" /> <path d=\"M12 17h.01\" />",
    shapes: [{"tag":"path","attrs":{"d":"M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"}},{"tag":"path","attrs":{"d":"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"}},{"tag":"path","attrs":{"d":"M12 17h.01"}}] },
  "icon.tool.todo": { glyph: "list-todo", license: "isc", svg: "<path d=\"M13 5h8\" /> <path d=\"M13 12h8\" /> <path d=\"M13 19h8\" /> <path d=\"m3 17 2 2 4-4\" /> <rect x=\"3\" y=\"4\" width=\"6\" height=\"6\" rx=\"1\" />",
    shapes: [{"tag":"path","attrs":{"d":"M13 5h8"}},{"tag":"path","attrs":{"d":"M13 12h8"}},{"tag":"path","attrs":{"d":"M13 19h8"}},{"tag":"path","attrs":{"d":"m3 17 2 2 4-4"}},{"tag":"rect","attrs":{"x":"3","y":"4","width":"6","height":"6","rx":"1"}}] },
  "icon.tool.mcp": { glyph: "plug", license: "isc", svg: "<path d=\"M12 22v-5\" /> <path d=\"M15 8V2\" /> <path d=\"M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z\" /> <path d=\"M9 8V2\" />",
    shapes: [{"tag":"path","attrs":{"d":"M12 22v-5"}},{"tag":"path","attrs":{"d":"M15 8V2"}},{"tag":"path","attrs":{"d":"M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z"}},{"tag":"path","attrs":{"d":"M9 8V2"}}] },
  "icon.tool.unknown": { glyph: "wrench", license: "isc", svg: "<path d=\"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z\" />",
    shapes: [{"tag":"path","attrs":{"d":"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z"}}] },
  "icon.agent.thinking": { glyph: "brain", license: "isc", svg: "<path d=\"M12 18V5\" /> <path d=\"M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4\" /> <path d=\"M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5\" /> <path d=\"M17.997 5.125a4 4 0 0 1 2.526 5.77\" /> <path d=\"M18 18a4 4 0 0 0 2-7.464\" /> <path d=\"M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517\" /> <path d=\"M6 18a4 4 0 0 1-2-7.464\" /> <path d=\"M6.003 5.125a4 4 0 0 0-2.526 5.77\" />",
    shapes: [{"tag":"path","attrs":{"d":"M12 18V5"}},{"tag":"path","attrs":{"d":"M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4"}},{"tag":"path","attrs":{"d":"M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5"}},{"tag":"path","attrs":{"d":"M17.997 5.125a4 4 0 0 1 2.526 5.77"}},{"tag":"path","attrs":{"d":"M18 18a4 4 0 0 0 2-7.464"}},{"tag":"path","attrs":{"d":"M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517"}},{"tag":"path","attrs":{"d":"M6 18a4 4 0 0 1-2-7.464"}},{"tag":"path","attrs":{"d":"M6.003 5.125a4 4 0 0 0-2.526 5.77"}}] },
  "icon.agent.approval": { glyph: "shield-check", license: "isc", svg: "<path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" /> <path d=\"m9 12 2 2 4-4\" />",
    shapes: [{"tag":"path","attrs":{"d":"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"}},{"tag":"path","attrs":{"d":"m9 12 2 2 4-4"}}] },
  "icon.agent.secret": { glyph: "key", license: "mit-feather", svg: "<path d=\"m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4\" /> <path d=\"m21 2-9.6 9.6\" /> <circle cx=\"7.5\" cy=\"15.5\" r=\"5.5\" />",
    shapes: [{"tag":"path","attrs":{"d":"m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4"}},{"tag":"path","attrs":{"d":"m21 2-9.6 9.6"}},{"tag":"circle","attrs":{"cx":"7.5","cy":"15.5","r":"5.5"}}] },
  "icon.agent.sudo": { glyph: "shield-alert", license: "isc", svg: "<path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" /> <path d=\"M12 8v4\" /> <path d=\"M12 16h.01\" />",
    shapes: [{"tag":"path","attrs":{"d":"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"}},{"tag":"path","attrs":{"d":"M12 8v4"}},{"tag":"path","attrs":{"d":"M12 16h.01"}}] },
  "icon.agent.voice": { glyph: "mic", license: "isc", svg: "<path d=\"M12 19v3\" /> <path d=\"M19 10v2a7 7 0 0 1-14 0v-2\" /> <rect x=\"9\" y=\"2\" width=\"6\" height=\"13\" rx=\"3\" />",
    shapes: [{"tag":"path","attrs":{"d":"M12 19v3"}},{"tag":"path","attrs":{"d":"M19 10v2a7 7 0 0 1-14 0v-2"}},{"tag":"rect","attrs":{"x":"9","y":"2","width":"6","height":"13","rx":"3"}}] },
  "icon.agent.attachment": { glyph: "paperclip", license: "isc", svg: "<path d=\"m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551\" />",
    shapes: [{"tag":"path","attrs":{"d":"m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551"}}] },
  "icon.agent.schedule": { glyph: "alarm-clock", license: "isc", svg: "<circle cx=\"12\" cy=\"13\" r=\"8\" /> <path d=\"M12 9v4l2 2\" /> <path d=\"M5 3 2 6\" /> <path d=\"m22 6-3-3\" /> <path d=\"M6.38 18.7 4 21\" /> <path d=\"M17.64 18.67 20 21\" />",
    shapes: [{"tag":"circle","attrs":{"cx":"12","cy":"13","r":"8"}},{"tag":"path","attrs":{"d":"M12 9v4l2 2"}},{"tag":"path","attrs":{"d":"M5 3 2 6"}},{"tag":"path","attrs":{"d":"m22 6-3-3"}},{"tag":"path","attrs":{"d":"M6.38 18.7 4 21"}},{"tag":"path","attrs":{"d":"M17.64 18.67 20 21"}}] },
  "icon.agent.plugin": { glyph: "puzzle", license: "isc", svg: "<path d=\"M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z\" />",
    shapes: [{"tag":"path","attrs":{"d":"M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z"}}] },
  "icon.agent.error": { glyph: "circle-alert", license: "isc", svg: "<circle cx=\"12\" cy=\"12\" r=\"10\" /> <line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\" /> <line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\" />",
    shapes: [{"tag":"circle","attrs":{"cx":"12","cy":"12","r":"10"}},{"tag":"line","attrs":{"x1":"12","x2":"12","y1":"8","y2":"12"}},{"tag":"line","attrs":{"x1":"12","x2":"12.01","y1":"16","y2":"16"}}] },
  "icon.agent.done": { glyph: "check", license: "mit-feather", svg: "<path d=\"M20 6 9 17l-5-5\" />",
    shapes: [{"tag":"path","attrs":{"d":"M20 6 9 17l-5-5"}}] },
  "icon.ui.archive": { glyph: "archive", license: "isc", svg: "<rect width=\"20\" height=\"5\" x=\"2\" y=\"3\" rx=\"1\" /> <path d=\"M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8\" /> <path d=\"M10 12h4\" />",
    shapes: [{"tag":"rect","attrs":{"width":"20","height":"5","x":"2","y":"3","rx":"1"}},{"tag":"path","attrs":{"d":"M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"}},{"tag":"path","attrs":{"d":"M10 12h4"}}] },
  "icon.ui.chat": { glyph: "message-circle", license: "isc", svg: "<path d=\"M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719\" />",
    shapes: [{"tag":"path","attrs":{"d":"M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"}}] },
  "icon.ui.find": { glyph: "search", license: "mit-feather", svg: "<path d=\"m21 21-4.34-4.34\" /> <circle cx=\"11\" cy=\"11\" r=\"8\" />",
    shapes: [{"tag":"path","attrs":{"d":"m21 21-4.34-4.34"}},{"tag":"circle","attrs":{"cx":"11","cy":"11","r":"8"}}] },
} as const satisfies Record<string, IconEntry>;

/** Every name in the family. Append-only: repoint a token, never rename it. */
export type IconToken = keyof typeof ICONS;

/** Lowercased tool wire name -> token. */
export const WIRE_NAMES: Readonly<Record<string, IconToken>> = {
  "bash": "icon.tool.terminal",
  "terminal": "icon.tool.terminal",
  "shell": "icon.tool.terminal",
  "run": "icon.tool.terminal",
  "read": "icon.tool.read",
  "read_file": "icon.tool.read",
  "view": "icon.tool.read",
  "write": "icon.tool.write",
  "write_file": "icon.tool.write",
  "edit": "icon.tool.edit",
  "multiedit": "icon.tool.edit",
  "notebookedit": "icon.tool.edit",
  "glob": "icon.tool.list",
  "ls": "icon.tool.list",
  "list_dir": "icon.tool.list",
  "grep": "icon.tool.search",
  "search": "icon.tool.search",
  "find": "icon.tool.search",
  "webfetch": "icon.tool.web.fetch",
  "browse": "icon.tool.web.fetch",
  "fetch": "icon.tool.web.fetch",
  "websearch": "icon.tool.web.search",
  "generate_image": "icon.tool.image",
  "image": "icon.tool.image",
  "skill": "icon.tool.skill",
  "task": "icon.tool.subagent",
  "agent": "icon.tool.subagent",
  "subagent": "icon.tool.subagent",
  "askuserquestion": "icon.tool.question",
  "todowrite": "icon.tool.todo",
  "todoread": "icon.tool.todo",
};

/** Any tool whose wire name starts with this is an MCP tool. */
export const MCP_PREFIX = "mcp__";
export const MCP_TOKEN = "icon.tool.mcp" satisfies IconToken;

/** The shared <svg> shell attributes — Lucide's grid, 2px round stroke. */
export const SVG_ATTRS = {
  "viewBox": "0 0 24 24",
  "fill": "none",
  "stroke": "currentColor",
  "strokeWidth": 2,
  "strokeLinecap": "round",
  "strokeLinejoin": "round",
  "minRenderSize": 14
} as const;
