// generate.ts — emits src/generated.ts from src/map.json.
//
// map.json is the source of truth for the icon family (design lab `icon-map`,
// signed off 2026-08-01). Every consumer is GENERATED from it, never hand-copied
// — a hand-copied glyph is the same failure mode as the Android client's
// MarmaladeTypes.kt drifting from the daemon's contracts.
//
// Run: pnpm --filter @marmalade/icons generate
// The `generated-in-sync` unit test fails the build if this wasn't re-run.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export interface RawEntry {
  glyph: string;
  source: string;
  license: string;
  svg: string;
  matches: string;
  wire?: string[];
  prefix?: string;
}

export interface RawMap {
  grid: Record<string, unknown>;
  tokens: Record<string, RawEntry>;
}

const MAP_PATH = fileURLToPath(new URL("../src/map.json", import.meta.url));
const OUT_PATH = fileURLToPath(new URL("../src/generated.ts", import.meta.url));

/** Split inner SVG markup into structured shapes, so renderers can build real
 *  elements instead of injecting HTML. Only self-closing geometry elements with
 *  plain (dash-free) attributes appear in the map; anything else is a bug in a
 *  pasted glyph and fails the build here rather than silently at runtime. */
export function parseShapes(svg: string): { tag: string; attrs: Record<string, string> }[] {
  const shapes: { tag: string; attrs: Record<string, string> }[] = [];
  const element = /<([a-z]+)((?:\s+[a-zA-Z][\w-]*="[^"]*")*)\s*\/>/g;
  let m: RegExpExecArray | null;
  while ((m = element.exec(svg)) !== null) {
    const attrs: Record<string, string> = {};
    for (const a of m[2].matchAll(/([a-zA-Z][\w-]*)="([^"]*)"/g)) {
      if (a[1].includes("-")) throw new Error(`unsupported attribute ${a[1]} in ${m[0]}`);
      attrs[a[1]] = a[2];
    }
    shapes.push({ tag: m[1], attrs });
  }
  // Nothing may be silently dropped: strip every matched element and the markup
  // must be empty. A glyph pasted with a <g>, a style or a nested element trips
  // this at generate time instead of vanishing from the render.
  const leftovers = svg.replace(element, "").trim();
  if (shapes.length === 0 || leftovers.length > 0) {
    throw new Error(`unparsable glyph markup (leftover: ${JSON.stringify(leftovers)}): ${svg}`);
  }
  return shapes;
}

/** The generated module text, as a pure function of the map — so the test can
 *  compare it against what is on disk without shelling out. */
export function renderGenerated(map: RawMap): string {
  const q = (s: string): string => JSON.stringify(s);
  const entries = Object.entries(map.tokens);

  const icons = entries
    .map(
      ([token, e]) =>
        `  ${q(token)}: { glyph: ${q(e.glyph)}, license: ${q(e.license)}, svg: ${q(e.svg)},\n    shapes: ${JSON.stringify(parseShapes(e.svg))} },`,
    )
    .join("\n");

  // wire name -> token. Built here so the resolver is a plain object lookup at
  // runtime instead of a scan over 28 entries per tool card.
  const wire: string[] = [];
  for (const [token, e] of entries) {
    for (const name of e.wire ?? []) wire.push(`  ${q(name)}: ${q(token)},`);
  }

  const mcpToken = entries.find(([, e]) => e.prefix === "mcp__")?.[0];
  if (!mcpToken) throw new Error("map.json: no token carries the mcp__ prefix");

  return `// GENERATED by scripts/generate.ts from src/map.json — DO NOT EDIT.
// Regenerate with: pnpm --filter @marmalade/icons generate

/** Which upstream license covers a glyph. Lucide's LICENSE is a DUAL license:
 *  ISC for Lucide originals, MIT (© Cole Bemis) for the icons it lists as
 *  derived from Feather. See LICENSE.lucide and the repo THIRD-PARTY-NOTICES.md. */
export type IconLicense = "isc" | "mit-feather";

export interface IconEntry {
  /** Upstream Lucide glyph name. */
  readonly glyph: string;
  readonly license: IconLicense;
  /** Inner SVG markup, to be wrapped in the shared 24x24 shell (see SVG_ATTRS). */
  readonly svg: string;
  /** The same drawing, parsed — so a renderer can build real elements instead
   *  of injecting markup. Attribute names are SVG-native and dash-free, so they
   *  pass straight through to React/JSX. */
  readonly shapes: readonly { readonly tag: string; readonly attrs: Readonly<Record<string, string>> }[];
}

export const ICONS = {
${icons}
} as const satisfies Record<string, IconEntry>;

/** Every name in the family. Append-only: repoint a token, never rename it. */
export type IconToken = keyof typeof ICONS;

/** Lowercased tool wire name -> token. */
export const WIRE_NAMES: Readonly<Record<string, IconToken>> = {
${wire.join("\n")}
};

/** Any tool whose wire name starts with this is an MCP tool. */
export const MCP_PREFIX = "mcp__";
export const MCP_TOKEN = ${q(mcpToken)} satisfies IconToken;

/** The shared <svg> shell attributes — Lucide's grid, 2px round stroke. */
export const SVG_ATTRS = ${JSON.stringify(map.grid, null, 2)} as const;
`;
}

export function loadMap(): RawMap {
  return JSON.parse(readFileSync(MAP_PATH, "utf8")) as RawMap;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT_PATH, renderGenerated(loadMap()));
  console.log(`wrote ${OUT_PATH}`);
}
